source 'https://rubygems.org'

spree_opts = if ENV['SPREE_PATH']
               { 'path': ENV['SPREE_PATH'] }
             else
               { 'github': 'spree/spree', 'branch': 'main', 'glob': 'spree/**/*.gemspec' }
             end
# spree provides the spree:install generator used by `rake test_app`
gem 'spree', spree_opts
gem 'spree_core', spree_opts
gem 'spree_api', spree_opts

gem 'spree_dev_tools', '>= 1.0.0.beta2'

# json 3.0 made JSON.parse options keyword-only, which Active Support 8.1 does
# not support yet. Remove the pin once Rails ships a compatible release.
gem 'json', '< 3'

if ENV['DB'] == 'mysql'
  gem 'mysql2'
elsif ENV['DB'] == 'postgres'
  gem 'pg'
else
  gem 'sqlite3', '>= 2.0'
end

gemspec
